### ISSUE TITLE
Unknown Kotlin JVM target 21

### ISSUE THREAD

**Issue by gabbe-swe** [datadirr/file_picker_pro#7]
FAILURE: Build failed with an exception.

* Where:
Build file '.pub-cache/hosted/pub.dev/file_picker_pro-2.0.0/android/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':file_picker_pro'.
> Unknown Kotlin JVM target: 21

Flutter :  3.29.2 
Dart :  3.7.2 
DevTools : 2.42.3
Gradle :  8.10.2

**Comment by Sahad2701** [comment]
This [commit](https://github.com/datadirr/file_picker_pro/pull/8/commits/32ddad6cd5cdd67301cba878ad2e0651b2afe8cf) fixes the Unknown Kotlin JVM target: 21 issue.

To use the fixed version:

```
file_picker_pro:
  git:
    url: https://github.com/datadirr/file_picker_pro.git
    ref: 32ddad6cd5cdd67301cba878ad2e0651b2afe8cf
```


Then run:

```
dart pub cache clean
flutter pub get
```

No more build issues — the plugin will now work smoothly with:

Flutter 3.29.2
Dart 3.7.2
Kotlin 2.1.0
Gradle 8.10.2
